# Generated by Django 4.0.5 on 2022-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_defaultminvalues_obtainedmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='obtainedmarks',
            name='div',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=10),
        ),
        migrations.AddField(
            model_name='obtainedmarks',
            name='name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obtainedmarks',
            name='registerNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obtainedmarks',
            name='rollNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obtainedmarks',
            name='std',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obtainedmarks',
            name='term',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=10),
        ),
    ]
