# Generated by Django 4.0.5 on 2022-06-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_obtainedmarks_div_obtainedmarks_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedmarks',
            name='div',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='obtainedmarks',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obtainedmarks',
            name='rollNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obtainedmarks',
            name='term',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
